
pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
queue_rules:
  - name: default
    queue_conditions:
      - or:
          - "#approved-reviews-by>=1"
          - author=renovate[bot]
          - and:
              - label=force
              - or:
                  - author=dastbe
      - check-success=ci-success
      - base=main
      - label!=changes-planned
    merge_conditions:
      - or:
          - "#approved-reviews-by>=1"
          - author=renovate[bot]
          - and:
              - label=force
              - or:
                  - author=dastbe
      - check-success=ci-success
    allow_inplace_checks: false
    merge_method: squash
