pull_request_rules:
  - name: default review rules
    conditions:
      - or:
          - "#approved-reviews-by>=1"
          - author=renovate[bot]
          - and:
              - label=force
              - or:
                  - author=dastbe
      - check-success=ci-success
      - base=main
      - label!=changes-planned
    actions:
      queue:
        name: default
        method: squash

queue_rules:
  - name: default
    conditions:
      - or:
          - "#approved-reviews-by>=1"
          - and:
              - label=force
              - or:
                  - author=dastbe
      - check-success=ci-success
    allow_inplace_checks: false
