# Override http_archive for local testing
local_repository(
    name = "contrib_rules_cdk",
    path = "../..",
)

#---SNIP--- Below here is re-used in the workspace snippet published on releases

######################
# rules_cdk setup #
######################
# Fetches the rules_cdk dependencies.
# If you want to have a different version of some dependency,
# you should fetch it *before* calling this.
# Alternatively, you can skip calling this function, so long as you've
# already fetched all the dependencies.
load("@contrib_rules_cdk//cdk:repositories.bzl", "rules_cdk_dependencies")

rules_cdk_dependencies()
